- name: Functions
  hosts: local
  connection: local
  vars:
    technologies: DevOps, Ansible, Shell, Linux
    Name: "Vijay Amudalapalli"
    gmail: VIJAY@GMAIL.COM
    ipaddress: 192.168.0.1

    tags:
      Application: Payment
      Environment: Dev
    
    ListTags:
    - key: Application
      value: Payment

    - key: Environment
      value: Dev

    
  tasks:

  - name: Printing Default Name
    ansible.builtin.debug:
      msg: "Hello {{ name | default('Vijay') }}"
  
  - name: List The Technologies
    ansible.builtin.debug:
      msg: "Technologies are : {{ technologies | split(',') }}"
  
  - name: Convert Maps To Lists
    ansible.builtin.debug:
      msg: "{{ tags | dict2items }}"

  - name: Convert Lists To Maps
    ansible.builtin.debug:
      msg: "{{ ListTags | items2dict }}"

  - name: Convert Upper Case
    ansible.builtin.debug:
      msg: "{{ Name | upper }}"

  - name: Convert Lower Case
    ansible.builtin.debug:
      msg: "{{ gmail | lower }}"

  - name: Check IP Valid OR Not
    ansible.builtin.debug:
      msg: "{{ ipaddress | ansible.utils.ipv4 }}"

