- name: Functions
  hosts: local
  connection: local
  vars:
    # technologies: DevOps, Ansible, Shell, Linux
    name: "Vijay Amudalapalli"
    # gmail: VIJAY@GMAIL.COM
    # ipaddress: 192.168.0.1

    # tags:
    #   Application: Payment
    #   Environment: Dev
    
    # ListTags:
    # - key: Application
    #   value: Payment

    # - key: Environment
    #   value: Dev

    
  tasks:

  - name: Printing Default Name
    ansible.builtin.debug:
      msg: "Hello {{ name | default('Vijay') }}"