- name: Checking User Exist or Not
  hosts: local
  connection: local

  become: yes

  tasks:
  - name: user existance check
    ansible.builtin.command: id roboshop
    register: user_check
  
  - name: printing
    ansible.builtin.debug:
      msg: "User : {{ user_check }}"